preclean.sh: Add check for Google Vendor
As having the error causes conflicts when building other devices.

error: vendor/google/lynx/Android.bp:5:1: module "soong_namespace": namespace device/google/lynx does not exist;
https://hel-eu-1.ci.evolution-x.org/job/10.X%20-%20A15/job/polaris/1/console